### ISSUE TITLE
Enable dev setup for local testing

### ISSUE THREAD

**Issue by barryels** [sebastiansandqvist/mithril-examples#2]
Currently, running the `npm start` script yields a `sh: 1: firebase: not found` error.
One quick-fix would be to add `firebase-tools` to devDependencies. (I've never had much fun with global deps ;)
Running `npm start` then yields `Error: HTTP Error: 401, The entered credentials were incorrect.`
Which makes sense... each firebase app has its owner and such.

I'm thinking [http-server](https://www.npmjs.com/package/http-server) might be a simple solution to getting a local dev server running.

**Comment by barryels** [comment]
Something like this:

https://github.com/barryels/mithril-examples/commit/5100d1485d9b295e46626910d7a8c0c872c31ef4

**Comment by sebastiansandqvist** [comment]
This is a good idea. I prefer to run it with `firebase-tools` directly since that is how it will be deployed, so that the local version runs with the same config and settings as the live version.

**Comment by sebastiansandqvist** [comment]
If you want to add that change in a pull request you're welcome to. Otherwise, I'm refactoring parts of this project this weekend and can include that in my changes.

**Comment by barryels** [comment]
Thank @sebastiansandqvist !

I've fetch / merged from your master and made the package.json changes. I'm going to be working on [this project](https://github.com/barryels/mithril-realworld-example-app) for a while, so won't be too active here for a week or so.

**Comment by sebastiansandqvist** [comment]
Should be fixed now by using superstatic instead of firebase for the local server.

**Comment by barryels** [comment]
Yup, it works! :)
