### ISSUE TITLE
Might need to update examples to newer version of Mithril

### ISSUE THREAD

**Issue by Bondifrench** [sebastiansandqvist/mithril-examples#5]
Your examples were invaluable but there are a few changes that will need to be reflected.
Notably `m.withAttr` and `m.prop()` do not exist any more. 
The first one has been simply eliminated, as some think arrow functions make it less verbose and easier to minify.
The second has been replaced with the more versatile streams as in `m.stream()`.

Cheers

**Comment by sebastiansandqvist** [comment]
Thanks you for pointing this out--thankfully the API didn't change too drastically from v1 to v2. I didn't find any occurrences of `m.prop` in my examples, but I replaced all the `m.withAttr` instances.
